version: "3.9"

networks:
  work_network:
    driver: bridge

services:
  db:
    container_name: hakaton_db
    image: postgres
    mem_limit: 1GB
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hakaton_api
    networks:
      - work_network

  redis:
    container_name: hakaton_redis
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - ./redis_data/d–∞ta:/root/redis
      - ./redis_data/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=root
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - work_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - work_network

  grafana:
      image: grafana/grafana:latest
      container_name: grafana
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
      ports:
        - "3000:3000"
      networks:
        - work_network

  app:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./src_data
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - work_network
