  global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 15s
  alerting:
    alertmanagers:
      - follow_redirects: true
        enable_http2: true
        scheme: http
        timeout: 10s
        api_version: v2
        static_configs:
          - targets: [ ]
  scrape_configs:
    - job_name: prometheus
      honor_timestamps: true
      scrape_interval: 15s
      scrape_timeout: 10s
      scheme: http
      follow_redirects: true
      enable_http2: true
      static_configs:
        - targets:
            - localhost:9090
    - job_name: 'fastapi'
      scrape_interval: 10s
      static_configs:
        - targets: [ 'fastapi_app:8000' ]
      metrics_path: "/custom_metrics"